services:
  - type: web
    name: showroom-backend
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8080
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: SUPABASE_BUCKET
        value: showrooms
      - key: PUBLIC_BASE_URL
        sync: false
      - key: ASSET_URL_TTL
        value: 3600
      - key: SESSION_COOKIE
        value: dev_portal_session
